exemple: https://web-api.coinmarketcap.com/v1/cryptocurrency/listings/historical?convert=USD,BTC&date=2021-04-25&limit=5000&start=201
first_day: 2013-04-28
database_path: P://Crypto//
price_database_path: P://Crypto//price_db//
coin_database_path: P://Crypto//coin_db//
data_sets: P://Crypto//datasets//
base_url: https://web-api.coinmarketcap.com/v1/cryptocurrency/listings/
methods: 
  - historical:
    parameters: 
      - convert
      - date
      - limit
      - start
