c_id                    , name                 
c_symbol                , slug                 
num_market_pairs        , date_added           
tags                    , max_supply           
circulating_supply      , total_supply         
platform_info           , cmc_rank             
platform_name           , platform_symbol  
last_updated            , BTC_price            
BTC_volume_24h          , BTC_percent_change_1h
BTC_percent_change_24h  , BTC_percent_change_7d
BTC_market_cap          , BTC_last_updated     
EUR_price               , EUR_volume_24h       
EUR_percent_change_1h   , EUR_percent_change_24
EUR_percent_change_7d   , EUR_market_cap       
EUR_last_updated        , USD_price            
USD_volume_24h          , USD_percent_change_1h
USD_percent_change_24h  , USD_percent_change_7d
USD_market_cap          , USD_last_updated     